# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-06 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline.contrib.web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancescheme',
            name='template',
        ),
        migrations.DeleteModel(
            name='InstanceScheme',
        ),
    ]
